// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFUe01b15sq5AtbZdh18e8pisEehmB-o4',
    appId: '1:659150266953:web:192bee38bbb3891ec2d598',
    messagingSenderId: '659150266953',
    projectId: 'rizzle-f9809',
    authDomain: 'rizzle-f9809.firebaseapp.com',
    storageBucket: 'rizzle-f9809.appspot.com',
    measurementId: 'G-YPNHJLECVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUpbsZKqM6kxUbmtQQX4WGgpUlPmFpEMc',
    appId: '1:659150266953:android:42e10318a52322b5c2d598',
    messagingSenderId: '659150266953',
    projectId: 'rizzle-f9809',
    storageBucket: 'rizzle-f9809.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpq8x1E-fSFAm7SPdPukLKJZxiwI-z5bg',
    appId: '1:659150266953:ios:f682adb56464c647c2d598',
    messagingSenderId: '659150266953',
    projectId: 'rizzle-f9809',
    storageBucket: 'rizzle-f9809.appspot.com',
    iosBundleId: 'com.example.rizzle',
  );
}
